language: ruby
cache: bundler
sudo: true
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=4.2.3"
services:
  - redis-server
before_install:
  - sudo apt-get update
  - sudo apt-get install -y clamav libclamav-dev
  - sudo freshclam --update-db=bytecode
before_script:
  - echo "test:"$'\n'"  secret_key_base:" $(rake secret) > config/secrets.yml
  - jdk_switcher use oraclejdk8
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake jetty:clean
  - bundle exec rake sufia:jetty:config
  - bundle exec rake jetty:start
